version: '3.8'

services:
  civcrm:
    image: civcrm/civicrm-core
    container_name: civcrm
    ports:
      - "8080:80"
    volumes:
      - ./civicrm:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: civcrm-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: civicrm
      MYSQL_USER: civicrm
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: nginx:latest
    container_name: civcrm-web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - civcrm

volumes:
  db_data:
